### ISSUE TITLE
Must install libmemcached to install pip dependencies on MacOS

### ISSUE THREAD

**Issue by Kieran-Broekhoven** [carltongibson/dcus2019sprints#1]
When running `pip3 install -r requirements/py3.txt` on MacOS Mojave, the following error appeared:

```
#include <libmemcached/memcached.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
```

This was resolved by running `brew install libmemcached`, which would be helpful to include in this documentation.

**Comment by davidmgvaz** [comment]
If you are using macports:

sudo port install libmemcached

Then, assuming you're using pip:

pip install pylibmc --install-option="--with-libmemcached=/opt/local"

or

LIBMEMCACHED=/opt/local pip install pylibmc
