### ISSUE TITLE
MacOS: disable fork safety to allow `runtests.py` to complete

### ISSUE THREAD

**Issue by FlipperPA** [carltongibson/dcus2019sprints#2]
We need to add this command to our `.bash_profiles` on Mac:

`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`

**Comment by carltongibson** [comment]
This is covered by [Django ticket #27086](https://code.djangoproject.com/ticket/27086), which'll be fixed by https://github.com/django/django/pull/11203, so I'll close this here. 

Thanks @FlipperPA! 👍
